### ISSUE TITLE
Dotty support meta issue

### ISSUE THREAD

**Issue by larsrh** [monix/monix#1311]
@Avasil and I are working towards Dotty support for Monix. This issue tracks everything that is needed for it.

* [x] Dotty for Minitest (monix/minitest#66)
* [x] Drop Scala 2.11 support and simplify source directories (#1312)
* [x] Drop Scala.js 0.6 support (#1312)
* [x] Update to CE 2.2.0 & Cats 2.2.0: #1266 (Dotty support is present in subsequent milestone releases)¹
* [x] Update implicitbox (monix/implicitbox#7, #1318)
* [x] Wait for scala-collection-compat (scala/scala-collection-compat#385)
* [x] ~Drop better-monadic-for (#1313 :question:)~

<hr>

Work in progress PR: #1323

<hr>

¹ side note on CE & Cats milestones: we will be releasing proper releases, but the more downstream libraries test Dotty support, the better

**Comment by larsrh** [comment]
Closing this since the corresponding PR is ready.
